//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.BC.TipoCambio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.bcn.gob.ni/", ConfigurationName="WS.BC.TipoCambio.Tipo_Cambio_BCNSoap")]
    public interface Tipo_Cambio_BCNSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.bcn.gob.ni/RecuperaTC_Dia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RecuperaTC_DiaAsync(int Ano, int Mes, int Dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.bcn.gob.ni/RecuperaTC_Mes", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.BC.TipoCambio.RecuperaTC_MesResponse> RecuperaTC_MesAsync(WS.BC.TipoCambio.RecuperaTC_MesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaTC_MesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaTC_Mes", Namespace="http://servicios.bcn.gob.ni/", Order=0)]
        public WS.BC.TipoCambio.RecuperaTC_MesRequestBody Body;
        
        public RecuperaTC_MesRequest()
        {
        }
        
        public RecuperaTC_MesRequest(WS.BC.TipoCambio.RecuperaTC_MesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios.bcn.gob.ni/")]
    public partial class RecuperaTC_MesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Ano;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Mes;
        
        public RecuperaTC_MesRequestBody()
        {
        }
        
        public RecuperaTC_MesRequestBody(int Ano, int Mes)
        {
            this.Ano = Ano;
            this.Mes = Mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaTC_MesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaTC_MesResponse", Namespace="http://servicios.bcn.gob.ni/", Order=0)]
        public WS.BC.TipoCambio.RecuperaTC_MesResponseBody Body;
        
        public RecuperaTC_MesResponse()
        {
        }
        
        public RecuperaTC_MesResponse(WS.BC.TipoCambio.RecuperaTC_MesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios.bcn.gob.ni/")]
    public partial class RecuperaTC_MesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RecuperaTC_MesResult;
        
        public RecuperaTC_MesResponseBody()
        {
        }
        
        public RecuperaTC_MesResponseBody(System.Xml.Linq.XElement RecuperaTC_MesResult)
        {
            this.RecuperaTC_MesResult = RecuperaTC_MesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface Tipo_Cambio_BCNSoapChannel : WS.BC.TipoCambio.Tipo_Cambio_BCNSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class Tipo_Cambio_BCNSoapClient : System.ServiceModel.ClientBase<WS.BC.TipoCambio.Tipo_Cambio_BCNSoap>, WS.BC.TipoCambio.Tipo_Cambio_BCNSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Tipo_Cambio_BCNSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Tipo_Cambio_BCNSoapClient.GetBindingForEndpoint(endpointConfiguration), Tipo_Cambio_BCNSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tipo_Cambio_BCNSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Tipo_Cambio_BCNSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tipo_Cambio_BCNSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Tipo_Cambio_BCNSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tipo_Cambio_BCNSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> RecuperaTC_DiaAsync(int Ano, int Mes, int Dia)
        {
            return base.Channel.RecuperaTC_DiaAsync(Ano, Mes, Dia);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.BC.TipoCambio.RecuperaTC_MesResponse> WS.BC.TipoCambio.Tipo_Cambio_BCNSoap.RecuperaTC_MesAsync(WS.BC.TipoCambio.RecuperaTC_MesRequest request)
        {
            return base.Channel.RecuperaTC_MesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.BC.TipoCambio.RecuperaTC_MesResponse> RecuperaTC_MesAsync(int Ano, int Mes)
        {
            WS.BC.TipoCambio.RecuperaTC_MesRequest inValue = new WS.BC.TipoCambio.RecuperaTC_MesRequest();
            inValue.Body = new WS.BC.TipoCambio.RecuperaTC_MesRequestBody();
            inValue.Body.Ano = Ano;
            inValue.Body.Mes = Mes;
            return ((WS.BC.TipoCambio.Tipo_Cambio_BCNSoap)(this)).RecuperaTC_MesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Tipo_Cambio_BCNSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Tipo_Cambio_BCNSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Tipo_Cambio_BCNSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Tipo_Cambio_BCNSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Tipo_Cambio_BCNSoap,
            
            Tipo_Cambio_BCNSoap12,
        }
    }
}
